### ISSUE TITLE
can't start the game

### ISSUE THREAD

**Issue by Cathyttt** [prompt-engineering/chat-visual-novel#6]
I'm sure I paste the correct api-key but I can't start the game. It's always loading.

![image](https://github.com/prompt-engineering/chat-visual-novel/assets/39302107/091065b5-d29e-483f-b7c2-ace4ef25eada)

**Comment by tianweiliu** [comment]
Please make sure either you choose "client mode" with a network that can reach openai, or you choose server mode (can also get blocked by openai).
